import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage();
page.on('console', msg => console.log('PAGE LOG:', msg.text()));
page.on('pageerror', error => console.log('PAGE ERROR:', error.message));
await page.goto('https://rexoco.netlify.app/', { waitUntil: 'domcontentloaded' });
await new Promise(r => setTimeout(r, 2000));
const html = await page.evaluate(() => document.body.innerHTML);
console.log('HTML CONTENT:', html);
await browser.close();
